[project]
name = "rascripts"
version = "0.1.0"
description = "It's Biendeo's RetroAchievements scripts!"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bitarray>=3.8.0",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
